openapi: 3.2.0
info:
  title: proto/cw_ztp_dynamic_config.proto Cwztpdynamicconfigs API
  version: 2.0.0
  x-provenance:
    method: harvested
    authored_by: Cisco Crosswork
    harvested_by: API Evangelist
    harvested_on: '2026-08-19'
    first_party: true
    note: Published by Cisco. Retrieved unmodified except for this x-provenance block.
    provider_published: true
  x-evidence:
  - type: source
    url: https://github.com/CiscoDevNet/crosswork-openapi-spec/blob/master/ZTP/2.0APIs/cw_ztp_dynamic_config.swagger.json
  - type: raw
    url: https://raw.githubusercontent.com/CiscoDevNet/crosswork-openapi-spec/master/ZTP/2.0APIs/cw_ztp_dynamic_config.swagger.json
tags:
- name: cwztpdynamicconfigs
paths:
  /v1/query/config:
    post:
      summary: 'GetDynamicConfigs API

        Retrieves a list of config attributes.

        This api takes dynamicConfigRequest as input, in which user can specifiy either one of configID or profile name as filter, or can specify both.

        Response Body: dynamicConfigResponse'
      operationId: GetDynamicConfigs
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cwztpsvcdynamicConfigResponse'
      tags:
      - cwztpdynamicconfigs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cwztpsvcdynamicConfigRequest'
        required: true
components:
  schemas:
    cwztpsvcdynamicConfigRequest:
      type: object
      properties:
        configId:
          type: string
        profileName:
          type: string
    cwztpsvcdynamicConfigResponse:
      type: object
      properties:
        profileName:
          type: string
        configId:
          type: string
        configAttributes:
          type: array
          items:
            type: string
        code:
          type: integer
          format: int32
        message:
          type: string
